### PR TITLE
Updated factory method to include injected routes param, fixing compatibi

### PR DESCRIPTION
**Pull request by JDStraughan**
Updated factory method to include injected routes param, fixing compatibility issue with parent method.

Hope this helps!

Thanks for a great module.

~Jason

### CODE REVIEW

**Comment by jeanmask** [comment]
Hi! Thanks for your contribution =)

**Comment by JDStraughan** [comment]
My pleasure.  I see you merged into 3.2/develop, any idea on when it will be merged into 3.2/master?

**Comment by jeanmask** [comment]
now ;)

**Comment by JDStraughan** [comment]
Thanks!

**Pull request merged**
